### ISSUE TITLE
As a maintainer of BDP, I want to create a mechanism to store also historical JSON based meta data, to compare meta data over time to see false inserts or to understand differences.

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-core#29]
Belongs to EPIC #28

- [x] Each Station must have a meta data record assigned
- [x] Each Station must have a history of meta data records as list
- [x] The actual meta data must be accessible directly, that is, no lookup needed
- [x] Remove all DTOs that are domain specific
- [x] Remove all DAL classes that are domain specific (only Measurement... and Elaboration... should remain as types)
- [x] Eliminate duplicate code between MeasurementStation and ElaborationStation and combine them if possible
- [x] Rewrite all queries to use the attribute `stationtype` instead of the class-name (coming from inheritance handling)
- [x] The old and new API must be accessible at the same time (api/v1/... and api/v2/...)
> We did not change the API, hence we will keep the old URL instead, until we create a new API version

**Comment by Piiit** [comment]
Done. We test this all together before the v2 release
